export const userActionTypes = {
  SET_TOKEN: "SET_TOKEN",
  ROLE: "ROLE",
  SET_USER_PROFILE: "SET_USER_PROFILE",
  GET_USER: "GET_USER",
  GET_USER_ERROR: "GET_USER_ERROR",
  GET_ORPHAN: "GET_ORPHAN",
  GET_ORPHAN_ERROR: "GET_ORPHAN_ERROR",
  FETCH_START: "FETCH_START",
};
